apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: vaultwarden
  namespace: argocd
spec:
  project: default
  sources:
    - repoURL: https://guerzon.github.io/vaultwarden
      chart: vaultwarden
      targetRevision: 0.46.1
      helm:
        valueFiles:
          - $values/k8s/apps/vaultwarden/values.yaml
    - repoURL: git@github.com:acwilsondev/homelab-docker.git
      targetRevision: main
      ref: values
  destination:
    server: https://kubernetes.default.svc
    namespace: vaultwarden
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
