apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: webui
  namespace: argocd
spec:
  project: default
  sources:
    - repoURL: https://bjw-s-labs.github.io/helm-charts
      chart: app-template
      targetRevision: 5.1.0
      helm:
        valueFiles:
          - $values/k8s/apps/webui/values.yaml
    - repoURL: git@github.com:acwilsondev/homelab-docker.git
      targetRevision: main
      ref: values
  destination:
    server: https://kubernetes.default.svc
    namespace: webui
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
